// components/ar-page.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef } from '@angular/core';
import { Subscription } from 'rxjs';
// FIX: GeolocationState is imported from types.ts, not from the service.
import { GeolocationService } from '../services/geolocation.service';
import { GeolocationState } from '../types';
import { DeviceOrientationService, DeviceOrientationState } from '../services/device-orientation.service';
import { MeasurementService } from '../services/measurement.service';
import { CoordService } from '../services/coord.service';
import { IndianGridCoordinates, IndianGridZone } from '../types';
import { LatLng } from 'leaflet';

interface ARData {
    distance: number | null;
    bearing: number | null;
    indianGrid: IndianGridCoordinates | null;
}

@Component({
  selector: 'app-ar-page',
  templateUrl: './ar-page.component.html',
})
export class ARPageComponent implements OnInit, OnDestroy {
    @ViewChild('video') videoRef: ElementRef<HTMLVideoElement>;
    private stream: MediaStream | null = null;
    permissionError: string | null = null;

    location: GeolocationState;
    orientation: DeviceOrientationState;
    arData: ARData = { distance: null, bearing: null, indianGrid: null };
    message: string | null = null;
    isAccuracyLow = false;

    private subscriptions: Subscription[] = [];

    readonly DEFAULT_INDIAN_GRID_ZONE = IndianGridZone.IIA;
    readonly MIN_PITCH_DEG = 15;
    readonly MAX_PITCH_DEG = 85;
    readonly DEVICE_HEIGHT_METERS = 1.5;
    readonly LOW_ACCURACY_THRESHOLD = 15;

    constructor(
        private geoService: GeolocationService,
        private orientationService: DeviceOrientationService,
        private measurementService: MeasurementService,
        private coordService: CoordService
    ) {}

    ngOnInit(): void {
        this.startCamera();
        const geoSub = this.geoService.location$.subscribe(loc => {
            this.location = loc;
            this.isAccuracyLow = loc.accuracy !== null && loc.accuracy > this.LOW_ACCURACY_THRESHOLD;
            this.updateARData();
        });
        const orientationSub = this.orientationService.state$.subscribe(orient => {
            this.orientation = orient;
            this.updateARData();
        });
        this.subscriptions.push(geoSub, orientationSub);
    }

    ngOnDestroy(): void {
        this.stopCamera();
        this.subscriptions.forEach(sub => sub.unsubscribe());
    }

    async startCamera(): Promise<void> {
        if (this.stream) return;
        try {
            this.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
            if (this.videoRef) this.videoRef.nativeElement.srcObject = this.stream;
            this.permissionError = null;
        } catch (err) {
            this.permissionError = "Camera access denied. Please grant permission.";
        }
    }

    stopCamera(): void {
        if (this.stream) {
            this.stream.getTracks().forEach(track => track.stop());
            this.stream = null;
            if (this.videoRef) this.videoRef.nativeElement.srcObject = null;
        }
    }

    updateARData(): void {
        const pitch = this.orientation?.pitch;
        const heading = this.orientation?.heading;

        // Reset and display message if conditions aren't met
        if (!this.location?.lat || !this.location?.lon || heading === null || pitch === null || pitch < this.MIN_PITCH_DEG || pitch > this.MAX_PITCH_DEG) {
            this.arData = { distance: null, bearing: null, indianGrid: null };
            this.updateMessage();
            return;
        }

        const distance = this.DEVICE_HEIGHT_METERS / Math.tan(pitch * (Math.PI / 180));
        if (distance < 0) return;

        const startPoint = new LatLng(this.location.lat, this.location.lon);
        const targetPoint = this.measurementService.calculateDestinationPoint(startPoint, heading, distance);
        
        this.arData = {
            distance,
            bearing: this.measurementService.calculateBearing(startPoint, targetPoint),
            indianGrid: this.coordService.convertLatLonToIndianGrid(targetPoint, this.DEFAULT_INDIAN_GRID_ZONE)
        };
        this.updateMessage();
    }
    
    updateMessage(): void {
        if (this.permissionError) { this.message = this.permissionError; return; }
        if (this.location?.error) { this.message = `GPS Error: ${this.location.error}`; return; }
        if (this.orientation?.pitch === null || this.orientation?.heading === null) { this.message = "Initializing sensors..."; return; }
        if (this.orientation.pitch < this.MIN_PITCH_DEG) { this.message = "Point device further down"; return; }
        if (this.orientation.pitch > this.MAX_PITCH_DEG) { this.message = "Aiming too close"; return; }
        this.message = null;
    }
}

<div class="h-full w-full relative bg-black">
    <video #video autoplay playsinline class="w-full h-full object-cover"></video>
    
    <div class="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
        <div class="crosshair-marker">+</div>
        <div *ngIf="arData.distance !== null && arData.bearing !== null && !message" class="ar-crosshair-data">
            <span>Dist: {{ arData.distance.toFixed(0) }}m</span>
            <span>Brg: {{ arData.bearing.toFixed(0) }}°</span>
        </div>
    </div>

    <div class="absolute top-4 left-4 right-4 z-10 pointer-events-auto">
         <div class="bg-gray-900/80 backdrop-blur-sm rounded-lg p-3 text-sm font-mono shadow-xl border border-[var(--color-surface-light)] w-full max-w-md mx-auto">
            <p class="info-panel-title text-center">CROSSHAIR TARGET</p>
            <div *ngIf="arData.indianGrid && !message; else messageTpl">
                <div class="grid grid-cols-2 gap-x-4 gap-y-1">
                    <div><p class="info-panel-label">Easting:</p><p class="text-lg">{{ arData.indianGrid.easting.toFixed(0) }}</p></div>
                    <div><p class="info-panel-label">Northing:</p><p class="text-lg">{{ arData.indianGrid.northing.toFixed(0) }}</p></div>
                    <div>
                        <p class="info-panel-label">Distance:</p>
                        <p class="text-lg" [class.text-yellow-400]="isAccuracyLow">
                            {{ arData.distance?.toFixed(0) }} <small>±{{ location?.accuracy?.toFixed(0) }}m</small>
                        </p>
                    </div>
                    <div><p class="info-panel-label">Bearing:</p><p class="text-lg">{{ arData.bearing?.toFixed(0) }}°</p></div>
                </div>
            </div>
            <ng-template #messageTpl>
                <div class="text-center text-lg text-[var(--color-text-secondary)] py-4 h-[76px] flex items-center justify-center">
                    <div *ngIf="permissionError" class="ar-message error"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-auto mb-2"><path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/><line x1="2" y1="2" x2="22" y2="22"/></svg><p>{{ permissionError }}</p></div>
                    <div *ngIf="location?.error && !permissionError" class="ar-message warning"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-auto mb-2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg><p>GPS Error: {{ location.error }}</p></div>
                    <p *ngIf="!permissionError && !location?.error">{{ message || "Acquiring lock..." }}</p>
                </div>
            </ng-template>
            <div *ngIf="isAccuracyLow" class="ar-message warning text-xs mt-2">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                Low GPS accuracy. Readings may be imprecise.
            </div>
         </div>
    </div>
</div>

// components/ARPage.tsx
import React, { useState, useEffect, useRef } from 'react';
import useGeolocation from '../hooks/useGeolocation';
import useDeviceOrientation from '../hooks/useDeviceOrientation';
import { calculateDestinationPoint, calculateBearing } from '../services/measurementService';
import { convertLatLonToIndianGrid } from '../services/coordService';
import { IndianGridCoordinates, IndianGridZone } from '../types';
import { CameraOff, AlertTriangle } from 'lucide-react';

const DEFAULT_INDIAN_GRID_ZONE = IndianGridZone.IIA;
const MIN_PITCH_DEG = 15;
const MAX_PITCH_DEG = 85;
const DEVICE_HEIGHT_METERS = 1.5;
const LOW_ACCURACY_THRESHOLD = 15; // meters

interface ARData {
    distance: number | null;
    bearing: number | null;
    indianGrid: IndianGridCoordinates | null;
}

const ARPage: React.FC<{ isVisible: boolean }> = ({ isVisible }) => {
    const videoRef = useRef<HTMLVideoElement>(null);
    const streamRef = useRef<MediaStream | null>(null);
    const [permissionError, setPermissionError] = useState<string | null>(null);
    
    const location = useGeolocation();
    const { heading, pitch } = useDeviceOrientation();
    
    const [arData, setArData] = useState<ARData>({ distance: null, bearing: null, indianGrid: null });

    useEffect(() => {
        const startCamera = async () => {
            if (streamRef.current) return;
            try {
                const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
                if (videoRef.current) videoRef.current.srcObject = stream;
                streamRef.current = stream;
                setPermissionError(null);
            } catch (err) {
                setPermissionError("Camera access denied. Please grant permission.");
            }
        };
        const stopCamera = () => {
            if (streamRef.current) {
                streamRef.current.getTracks().forEach(track => track.stop());
                streamRef.current = null;
                if (videoRef.current) videoRef.current.srcObject = null;
            }
        };
        if (isVisible) startCamera();
        else stopCamera();
        return stopCamera;
    }, [isVisible]);

    useEffect(() => {
        if (!isVisible || !location.lat || !location.lon || heading === null || pitch === null || pitch < MIN_PITCH_DEG || pitch > MAX_PITCH_DEG) {
            setArData({ distance: null, bearing: null, indianGrid: null });
            return;
        }

        const distance = DEVICE_HEIGHT_METERS / Math.tan(pitch * (Math.PI / 180));
        if (distance < 0) return;

        const startPoint = { lat: location.lat, lng: location.lon };
        const targetPoint = calculateDestinationPoint(startPoint, heading, distance);
        
        setArData({
            distance,
            bearing: calculateBearing(startPoint, targetPoint),
            indianGrid: convertLatLonToIndianGrid(targetPoint, DEFAULT_INDIAN_GRID_ZONE)
        });

    }, [isVisible, location, heading, pitch]);
    
    const getMessage = () => {
        if (permissionError) return <div className="ar-message error"><CameraOff className="mx-auto mb-2" size={32} /><p>{permissionError}</p></div>;
        if (location.error) return <div className="ar-message warning"><AlertTriangle className="mx-auto mb-2" size={32} /><p>GPS Error: {location.error}</p></div>;
        if (pitch === null || heading === null) return <p>Initializing sensors...</p>;
        if (pitch < MIN_PITCH_DEG) return <p>Point device further down</p>;
        if (pitch > MAX_PITCH_DEG) return <p>Aiming too close</p>;
        return null;
    };

    const message = getMessage();
    const isAccuracyLow = location.accuracy !== null && location.accuracy > LOW_ACCURACY_THRESHOLD;

    return (
        <div className="h-full w-full relative bg-black">
            <video ref={videoRef} autoPlay playsInline className="w-full h-full object-cover"></video>
            <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                <div className="crosshair-marker">+</div>
                {arData.distance !== null && arData.bearing !== null && !message && (
                    <div className="ar-crosshair-data">
                        <span>Dist: {arData.distance.toFixed(0)}m</span>
                        <span>Brg: {arData.bearing.toFixed(0)}°</span>
                    </div>
                )}
            </div>
            <div className="absolute top-4 left-4 right-4 z-10 pointer-events-auto">
                 <div className="bg-gray-900/80 backdrop-blur-sm rounded-lg p-3 text-sm font-mono shadow-xl border border-[var(--color-surface-light)] w-full max-w-md mx-auto">
                    <p className="info-panel-title text-center">CROSSHAIR TARGET</p>
                    {arData.indianGrid && !message ? (
                        <div className="grid grid-cols-2 gap-x-4 gap-y-1">
                            <div><p className="info-panel-label">Easting:</p><p className="text-lg">{arData.indianGrid.easting.toFixed(0)}</p></div>
                            <div><p className="info-panel-label">Northing:</p><p className="text-lg">{arData.indianGrid.northing.toFixed(0)}</p></div>
                            <div><p className="info-panel-label">Distance:</p><p className={`text-lg ${isAccuracyLow ? 'text-yellow-400' : ''}`}>{arData.distance?.toFixed(0)} <small>±{location.accuracy?.toFixed(0)}m</small></p></div>
                            <div><p className="info-panel-label">Bearing:</p><p className="text-lg">{arData.bearing?.toFixed(0)}°</p></div>
                        </div>
                    ) : (
                        <div className="text-center text-lg text-[var(--color-text-secondary)] py-4 h-[76px] flex items-center justify-center">{message || "Acquiring lock..."}</div>
                    )}
                    {isAccuracyLow && <div className="ar-message warning text-xs mt-2"><AlertTriangle size={16} className="mr-2"/>Low GPS accuracy. Readings may be imprecise.</div>}
                 </div>
            </div>
        </div>
    );
};

export default ARPage;
