// components/CompassPage.tsx
import React, { useState, useEffect } from 'react';
import useDeviceOrientation from '../hooks/useDeviceOrientation';
import { SlidersHorizontal } from 'lucide-react';

const CalibrationPanel: React.FC<{
    offset: number;
    onOffsetChange: (offset: number) => void;
    onClose: () => void;
}> = ({ offset, onOffsetChange, onClose }) => {
    const [localOffset, setLocalOffset] = useState(offset.toFixed(1));

    useEffect(() => { setLocalOffset(offset.toFixed(1)); }, [offset]);
    
    const handleApply = () => { onOffsetChange(parseFloat(localOffset) || 0); };
    const handleQuickAdjust = (val: number) => { onOffsetChange(offset + val); };
    
    return (
        <div className="fixed inset-0 bg-black/70 z-30 flex items-center justify-center" onClick={onClose}>
            <div className="bg-[var(--color-surface)] p-4 rounded-lg shadow-2xl border border-[var(--color-surface-light)] w-11/12 max-w-sm" onClick={e => e.stopPropagation()}>
                <h3 className="text-lg font-bold text-center mb-3">Compass Calibration</h3>
                <div className="flex items-center justify-center space-x-2 mb-3">
                    <span className="text-sm text-[var(--color-text-secondary)]">Offset:</span>
                    <input type="number" step="0.1" value={localOffset} onChange={(e) => setLocalOffset(e.target.value)} onBlur={handleApply} className="w-24 bg-[var(--color-background)] text-center text-lg font-mono p-1 rounded border border-[var(--color-surface-lighter)] focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)]" />
                    <span className="text-lg">°</span>
                </div>
                <div className="grid grid-cols-4 gap-2 text-sm mb-4">
                    <button onClick={() => handleQuickAdjust(-10)} className="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">-10</button>
                    <button onClick={() => handleQuickAdjust(-1)} className="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">-1</button>
                    <button onClick={() => handleQuickAdjust(1)} className="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">+1</button>
                    <button onClick={() => handleQuickAdjust(10)} className="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">+10</button>
                </div>
                <div className="grid grid-cols-2 gap-2">
                    <button onClick={() => onOffsetChange(0)} className="w-full bg-[var(--color-danger)]/80 hover:bg-[var(--color-danger)] text-white font-semibold py-2 px-4 rounded transition-colors">Reset</button>
                    <button onClick={onClose} className="w-full bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white font-bold py-2 px-4 rounded transition-colors">Done</button>
                </div>
            </div>
        </div>
    );
};

const CompassPage: React.FC = () => {
    const { heading, accuracy, error, requestPermission } = useDeviceOrientation();
    const [calibrationOffset, setCalibrationOffset] = useState<number>(0);
    const [isCalibrating, setIsCalibrating] = useState(false);

    useEffect(() => {
        const savedOffset = localStorage.getItem('compassCalibrationOffset');
        if (savedOffset) setCalibrationOffset(parseFloat(savedOffset));
    }, []);

    const handleSetOffset = (newOffset: number) => {
        setCalibrationOffset(newOffset);
        localStorage.setItem('compassCalibrationOffset', newOffset.toString());
    };

    const getDirection = (h: number | null) => {
        if (h === null) return '--';
        const dirs = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'];
        return dirs[Math.round(h / 22.5) % 16];
    };

    const displayHeading = heading !== null ? (heading + calibrationOffset + 360) % 360 : null;

    return (
        <div className="h-full w-full flex flex-col items-center justify-center bg-[var(--color-background)] p-4 text-white overflow-hidden">
            <h1 className="text-xl font-bold text-center text-[var(--color-accent-hover)] mb-4 flex-shrink-0">Compass</h1>
            <div className="relative w-72 h-72 sm:w-80 sm:h-80 flex items-center justify-center flex-shrink-0">
                <svg className="absolute w-full h-full" viewBox="0 0 200 200">
                    <defs>
                        <radialGradient id="bezelGradient" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
                            <stop offset="85%" stopColor="var(--color-surface)" />
                            <stop offset="100%" stopColor="var(--color-surface-lighter)" />
                        </radialGradient>
                        <filter id="innerShadow"><feGaussianBlur in="SourceAlpha" stdDeviation="2" result="blur" /><feOffset in="blur" dx="0" dy="0" result="offsetBlur" /><feFlood floodColor="#000" floodOpacity="0.5" result="flood" /><feComposite in="flood" in2="offsetBlur" operator="in" result="shadow" /><feComposite in="SourceGraphic" in2="shadow" operator="over" /></filter>
                    </defs>
                    <circle cx="100" cy="100" r="100" fill="url(#bezelGradient)" />
                    <circle cx="100" cy="100" r="96" fill="transparent" stroke="var(--color-background)" strokeWidth="1" filter="url(#innerShadow)"/>
                </svg>
                <div className="absolute w-[96%] h-[96%] transition-transform duration-100 ease-linear" style={{ transform: `rotate(${-displayHeading}deg)` }}>
                    <svg viewBox="0 0 200 200" className="w-full h-full">
                        <circle cx="100" cy="100" r="96" fill="var(--color-surface)" />
                        {Array.from({ length: 72 }).map((_, i) => {
                            const angle = i * 5; const isMajor = angle % 15 === 0; const isCardinal = angle % 90 === 0;
                            return <line key={`deg-${angle}`} x1="100" y1="8" x2="100" y2={isCardinal ? "22" : isMajor ? "16" : "12"} stroke="var(--color-text-secondary)" strokeWidth={isMajor ? "1" : "0.5"} transform={`rotate(${angle} 100 100)`} />;
                        })}
                        {['N', 'E', 'S', 'W'].map((dir, i) => <text key={dir} x="100" y="32" textAnchor="middle" fill={dir === 'N' ? 'var(--color-danger)' : 'var(--color-text-primary)'} fontSize="16" fontWeight="bold" transform={`rotate(${i * 90} 100 100)`}>{dir}</text>)}
                        {['NE', 'SE', 'SW', 'NW'].map((dir, i) => <text key={dir} x="100" y="32" textAnchor="middle" fill="var(--color-text-secondary)" fontSize="12" transform={`rotate(${45 + i * 90} 100 100)`}>{dir}</text>)}
                    </svg>
                </div>
                <div className="compass-needle" />
                <div className="absolute w-2.5 h-2.5 bg-gray-500 rounded-full border-2 border-gray-400 z-10"></div>
            </div>
            <div className="text-center my-4 p-4 bg-[var(--color-surface)] rounded-lg w-52 border border-[var(--color-surface-light)] flex-shrink-0">
                <div className="text-5xl font-mono">{displayHeading !== null ? displayHeading.toFixed(0) : '---'}<span className="text-3xl align-top">°</span></div>
                <div className="text-xl text-[var(--color-accent-hover)] font-semibold">{getDirection(displayHeading)}</div>
                {accuracy !== null && <div className="text-xs text-[var(--color-text-secondary)] font-mono">±{accuracy.toFixed(0)}°</div>}
            </div>
            <button onClick={() => setIsCalibrating(true)} className="absolute top-4 right-4 p-2 rounded-full bg-[var(--color-surface)] hover:bg-[var(--color-surface-light)] transition-colors" title="Calibrate Compass"><SlidersHorizontal size={20} /></button>
            {isCalibrating && <CalibrationPanel offset={calibrationOffset} onOffsetChange={handleSetOffset} onClose={() => setIsCalibrating(false)} />}
            {error && (
                <div className="mt-4 text-center">
                    <p className="text-red-400">{error}</p>
                    {error.includes("permission") && <button onClick={requestPermission} className="mt-2 bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white font-bold py-2 px-4 rounded">Grant Permission</button>}
                </div>
            )}
        </div>
    );
};

export default CompassPage;

// components/compass-page.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { DeviceOrientationService, DeviceOrientationState } from '../services/device-orientation.service';

@Component({
  selector: 'app-compass-page',
  templateUrl: './compass-page.component.html',
})
export class CompassPageComponent implements OnInit, OnDestroy {
  orientation: DeviceOrientationState;
  private orientationSub: Subscription;
  
  calibrationOffset = 0;
  isCalibrating = false;
  displayHeading: number | null = null;

  constructor(public orientationService: DeviceOrientationService) {}

  ngOnInit(): void {
    const savedOffset = localStorage.getItem('compassCalibrationOffset');
    if (savedOffset) this.calibrationOffset = parseFloat(savedOffset);

    this.orientationSub = this.orientationService.state$.subscribe(orientation => {
      this.orientation = orientation;
      this.displayHeading = orientation.heading !== null ? (orientation.heading + this.calibrationOffset + 360) % 360 : null;
    });
  }

  ngOnDestroy(): void {
    this.orientationSub.unsubscribe();
  }

  handleSetOffset(newOffset: number): void {
    this.calibrationOffset = newOffset;
    localStorage.setItem('compassCalibrationOffset', newOffset.toString());
  }

  getDirection(h: number | null): string {
    if (h === null) return '--';
    const dirs = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'];
    return dirs[Math.round(h / 22.5) % 16];
  }
}

<div class="h-full w-full flex flex-col items-center justify-center bg-[var(--color-background)] p-4 text-white overflow-hidden" *ngIf="orientation">
    <h1 class="text-xl font-bold text-center text-[var(--color-accent-hover)] mb-4 flex-shrink-0">Compass</h1>
    
    <div class="relative w-72 h-72 sm:w-80 sm:h-80 flex items-center justify-center flex-shrink-0">
        <svg class="absolute w-full h-full" viewBox="0 0 200 200">
            <defs>
                <radialGradient id="bezelGradient" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
                    <stop offset="85%" stop-color="var(--color-surface)" />
                    <stop offset="100%" stop-color="var(--color-surface-lighter)" />
                </radialGradient>
                <filter id="innerShadow"><feGaussianBlur in="SourceAlpha" stdDeviation="2" result="blur" /><feOffset in="blur" dx="0" dy="0" result="offsetBlur" /><feFlood flood-color="#000" flood-opacity="0.5" result="flood" /><feComposite in="flood" in2="offsetBlur" operator="in" result="shadow" /><feComposite in="SourceGraphic" in2="shadow" operator="over" /></filter>
            </defs>
            <circle cx="100" cy="100" r="100" fill="url(#bezelGradient)" />
            <circle cx="100" cy="100" r="96" fill="transparent" stroke="var(--color-background)" stroke-width="1" filter="url(#innerShadow)"/>
        </svg>
        <div class="absolute w-[96%] h-[96%] transition-transform duration-100 ease-linear" [style.transform]="'rotate(' + (-displayHeading) + 'deg)'">
            <svg viewBox="0 0 200 200" class="w-full h-full">
                <circle cx="100" cy="100" r="96" fill="var(--color-surface)" />
                <line *ngFor="let i of [].constructor(72); let idx = index"
                    [attr.x1]="100" [attr.y1]="8" 
                    [attr.x2]="100" [attr.y2]="(idx * 5 % 90 === 0) ? 22 : (idx * 5 % 15 === 0) ? 16 : 12"
                    stroke="var(--color-text-secondary)" 
                    [attr.stroke-width]="(idx * 5 % 15 === 0) ? 1 : 0.5"
                    [attr.transform]="'rotate(' + (idx * 5) + ' 100 100)'" />
                <text *ngFor="let dir of ['N', 'E', 'S', 'W']; let i = index" 
                    x="100" y="32" text-anchor="middle" [attr.fill]="dir === 'N' ? 'var(--color-danger)' : 'var(--color-text-primary)'" 
                    font-size="16" font-weight="bold" [attr.transform]="'rotate(' + (i * 90) + ' 100 100)'">{{dir}}</text>
                <text *ngFor="let dir of ['NE', 'SE', 'SW', 'NW']; let i = index" 
                    x="100" y="32" text-anchor="middle" fill="var(--color-text-secondary)" 
                    font-size="12" [attr.transform]="'rotate(' + (45 + i * 90) + ' 100 100)'">{{dir}}</text>
            </svg>
        </div>
        <div class="compass-needle"></div>
        <div class="absolute w-2.5 h-2.5 bg-gray-500 rounded-full border-2 border-gray-400 z-10"></div>
    </div>

    <div class="text-center my-4 p-4 bg-[var(--color-surface)] rounded-lg w-52 border border-[var(--color-surface-light)] flex-shrink-0">
        <div class="text-5xl font-mono">{{ displayHeading !== null ? displayHeading.toFixed(0) : '---' }}<span class="text-3xl align-top">°</span></div>
        <div class="text-xl text-[var(--color-accent-hover)] font-semibold">{{ getDirection(displayHeading) }}</div>
        <div *ngIf="orientation.accuracy !== null" class="text-xs text-[var(--color-text-secondary)] font-mono">±{{ orientation.accuracy.toFixed(0) }}°</div>
    </div>
    
    <button (click)="isCalibrating = true" class="absolute top-4 right-4 p-2 rounded-full bg-[var(--color-surface)] hover:bg-[var(--color-surface-light)] transition-colors" title="Calibrate Compass">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>
    </button>
    
    <div *ngIf="isCalibrating" class="fixed inset-0 bg-black/70 z-30 flex items-center justify-center" (click)="isCalibrating = false">
        <div class="bg-[var(--color-surface)] p-4 rounded-lg shadow-2xl border border-[var(--color-surface-light)] w-11/12 max-w-sm" (click)="$event.stopPropagation()">
            <h3 class="text-lg font-bold text-center mb-3">Compass Calibration</h3>
            <div class="flex items-center justify-center space-x-2 mb-3">
                <span class="text-sm text-[var(--color-text-secondary)]">Offset:</span>
                <input type="number" step="0.1" [value]="calibrationOffset" #offsetInput (change)="handleSetOffset(offsetInput.valueAsNumber)" class="w-24 bg-[var(--color-background)] text-center text-lg font-mono p-1 rounded border border-[var(--color-surface-lighter)] focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)]" />
                <span class="text-lg">°</span>
            </div>
            <div class="grid grid-cols-4 gap-2 text-sm mb-4">
                <button (click)="handleSetOffset(calibrationOffset - 10)" class="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">-10</button>
                <button (click)="handleSetOffset(calibrationOffset - 1)" class="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">-1</button>
                <button (click)="handleSetOffset(calibrationOffset + 1)" class="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">+1</button>
                <button (click)="handleSetOffset(calibrationOffset + 10)" class="p-2 rounded bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)]">+10</button>
            </div>
            <div class="grid grid-cols-2 gap-2">
                <button (click)="handleSetOffset(0)" class="w-full bg-[var(--color-danger)]/80 hover:bg-[var(--color-danger)] text-white font-semibold py-2 px-4 rounded transition-colors">Reset</button>
                <button (click)="isCalibrating = false" class="w-full bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white font-bold py-2 px-4 rounded transition-colors">Done</button>
            </div>
        </div>
    </div>
    
    <div *ngIf="orientation.error" class="mt-4 text-center">
        <p class="text-red-400">{{ orientation.error }}</p>
        <button *ngIf="orientation.error.includes('permission')" (click)="orientationService.requestPermission()" class="mt-2 bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white font-bold py-2 px-4 rounded">Grant Permission</button>
    </div>
</div>
