// components/DrawingTools.tsx
import React from 'react';
import { Ruler, Pen, Trash2 } from 'lucide-react';
import { DrawingTool } from '../types';

interface DrawingToolsProps {
    activeTool: DrawingTool;
    onToolSelect: (tool: DrawingTool) => void;
    onClear: () => void;
    drawingColor: string;
    onColorChange: (color: string) => void;
    drawingWeight: number;
    onWeightChange: (weight: number) => void;
}

const DrawingTools: React.FC<DrawingToolsProps> = ({ activeTool, onToolSelect, onClear, drawingColor, onColorChange, drawingWeight, onWeightChange }) => {
    const [isOpen, setIsOpen] = React.useState(false);

    const handleToolClick = (tool: DrawingTool) => {
        onToolSelect(activeTool === tool ? DrawingTool.None : tool);
    };
    
    const toolOptions = [
        { id: DrawingTool.Pen, name: 'Pen Tool', icon: <Pen size={18} /> },
    ];

    const colors = [
        { id: 'accent', value: '#f59e0b' }, // amber-500
        { id: 'blue', value: '#3b82f6' }, // blue-500
        { id: 'red', value: '#ef4444' }, // red-500
    ];

    return (
        <div className="relative">
            <button
                onClick={() => setIsOpen(!isOpen)}
                className={`p-2.5 rounded-full text-white w-12 h-12 flex items-center justify-center shadow-lg transition-colors ${activeTool !== DrawingTool.None ? 'bg-amber-500 hover:bg-amber-400' : 'bg-slate-700 hover:bg-slate-600'}`}
                aria-label="Drawing and Measurement Tools"
                title="Drawing and Measurement Tools"
            >
                <Ruler className="h-5 w-5" />
            </button>

            {isOpen && (
                <div className="absolute bottom-full mb-2 right-0 w-48 bg-[var(--color-surface)] border border-[var(--color-surface-light)] rounded-lg shadow-lg animate-fade-in-fast">
                    <ul className="p-1">
                        {toolOptions.map((option) => (
                            <li key={option.id}>
                                <button
                                    onClick={() => handleToolClick(option.id)}
                                    className={`w-full flex items-center space-x-2 text-left px-3 py-2 text-sm rounded-md transition-colors ${
                                        activeTool === option.id
                                            ? 'bg-[var(--color-accent)] text-white'
                                            : 'hover:bg-[var(--color-surface-light)] text-[var(--color-text-primary)]'
                                    }`}
                                >
                                    {option.icon}
                                    <span>{option.name}</span>
                                </button>
                            </li>
                        ))}
                        <li><div className="h-px bg-[var(--color-surface-light)] my-1"></div></li>
                        <li className="px-3 pt-1 pb-2">
                             <div className="text-xs text-[var(--color-text-secondary)] mb-2">Color</div>
                             <div className="flex justify-around">
                                {colors.map(color => (
                                    <button
                                        key={color.id}
                                        onClick={() => onColorChange(color.value)}
                                        className={`w-6 h-6 rounded-full transition-transform transform hover:scale-110 ${drawingColor === color.value ? 'ring-2 ring-offset-2 ring-offset-[var(--color-surface)] ring-white' : ''}`}
                                        style={{ backgroundColor: color.value }}
                                        aria-label={`Set color to ${color.id}`}
                                    />
                                ))}
                            </div>
                        </li>
                        <li className="px-3 pt-1 pb-2">
                             <div className="text-xs text-[var(--color-text-secondary)] mb-1">Thickness</div>
                             <div className="flex items-center space-x-2">
                                <input
                                    type="range"
                                    min="1"
                                    max="5"
                                    step="1"
                                    value={drawingWeight}
                                    onChange={(e) => onWeightChange(parseInt(e.target.value, 10))}
                                    className="w-full h-2 bg-slate-600 rounded-lg appearance-none cursor-pointer"
                                />
                                <span className="text-sm font-mono">{drawingWeight}px</span>
                             </div>
                        </li>
                         <li>
                             <div className="h-px bg-[var(--color-surface-light)] my-1"></div>
                            <button
                                onClick={() => { onClear(); setIsOpen(false); }}
                                className="w-full flex items-center space-x-2 text-left px-3 py-2 text-sm rounded-md transition-colors hover:bg-red-900/50 text-[var(--color-danger)]"
                            >
                                <Trash2 size={18} />
                                <span>Clear Drawings</span>
                            </button>
                        </li>
                    </ul>
                </div>
            )}
            <style>{`
                @keyframes fade-in-fast {
                    from { opacity: 0; transform: scale(0.95) translateY(10px); }
                    to { opacity: 1; transform: scale(1) translateY(0); }
                }
                .animate-fade-in-fast {
                    animation: fade-in-fast 0.1s ease-out forwards;
                }
            `}</style>
        </div>
    );
};

export default DrawingTools;

// components/drawing-tools.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { DrawingTool } from '../types';

@Component({
  selector: 'app-drawing-tools',
  templateUrl: './drawing-tools.component.html',
})
export class DrawingToolsComponent {
  @Input() activeTool: DrawingTool;
  @Input() drawingColor: string;
  @Input() drawingWeight: number;
  @Output() toolSelect = new EventEmitter<DrawingTool>();
  @Output() clear = new EventEmitter<void>();
  @Output() colorChange = new EventEmitter<string>();
  @Output() weightChange = new EventEmitter<number>();

  isOpen = false;
  
  toolOptions = [{ id: DrawingTool.Pen, name: 'Pen Tool' }];
  colors = [
    { id: 'accent', value: '#f59e0b' },
    { id: 'blue', value: '#3b82f6' },
    { id: 'red', value: '#ef4444' },
  ];
  
  readonly DrawingTool = DrawingTool;

  handleToolClick(tool: DrawingTool): void {
    this.toolSelect.emit(this.activeTool === tool ? DrawingTool.None : tool);
  }

  handleClear(): void {
    this.clear.emit();
    this.isOpen = false;
  }
}

<div class="relative">
    <button (click)="isOpen = !isOpen" class="p-2.5 rounded-full text-white w-12 h-12 flex items-center justify-center shadow-lg transition-colors"
        [ngClass]="activeTool !== DrawingTool.None ? 'bg-amber-500 hover:bg-amber-400' : 'bg-slate-700 hover:bg-slate-600'"
        aria-label="Drawing and Measurement Tools" title="Drawing and Measurement Tools">
        <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21.17 2.83l-8.34 8.34M3 21l8.34-8.34"/><path d="M21 12v6a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3h6"/></svg>
    </button>
    <div *ngIf="isOpen" class="absolute bottom-full mb-2 right-0 w-48 bg-[var(--color-surface)] border border-[var(--color-surface-light)] rounded-lg shadow-lg animate-fade-in-fast">
        <ul class="p-1">
            <li *ngFor="let option of toolOptions">
                <button (click)="handleToolClick(option.id)" class="w-full flex items-center space-x-2 text-left px-3 py-2 text-sm rounded-md transition-colors"
                    [ngClass]="activeTool === option.id ? 'bg-[var(--color-accent)] text-white' : 'hover:bg-[var(--color-surface-light)] text-[var(--color-text-primary)]'">
                    <svg *ngIf="option.id === DrawingTool.Pen" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                    <span>{{ option.name }}</span>
                </button>
            </li>
            <li><div class="h-px bg-[var(--color-surface-light)] my-1"></div></li>
            <li class="px-3 pt-1 pb-2">
                 <div class="text-xs text-[var(--color-text-secondary)] mb-2">Color</div>
                 <div class="flex justify-around">
                    <button *ngFor="let color of colors" (click)="colorChange.emit(color.value)"
                        class="w-6 h-6 rounded-full transition-transform transform hover:scale-110"
                        [class.ring-2]="drawingColor === color.value"
                        [class.ring-offset-2]="drawingColor === color.value"
                        [class.ring-offset-[var(--color-surface)]]="drawingColor === color.value"
                        [class.ring-white]="drawingColor === color.value"
                        [style.backgroundColor]="color.value" [attr.aria-label]="'Set color to ' + color.id"></button>
                </div>
            </li>
            <li class="px-3 pt-1 pb-2">
                 <div class="text-xs text-[var(--color-text-secondary)] mb-1">Thickness</div>
                 <div class="flex items-center space-x-2">
                    <input type="range" min="1" max="5" step="1" [value]="drawingWeight" (input)="weightChange.emit($any($event.target).valueAsNumber)" class="w-full h-2 bg-slate-600 rounded-lg appearance-none cursor-pointer" />
                    <span class="text-sm font-mono">{{ drawingWeight }}px</span>
                 </div>
            </li>
             <li>
                 <div class="h-px bg-[var(--color-surface-light)] my-1"></div>
                <button (click)="handleClear()" class="w-full flex items-center space-x-2 text-left px-3 py-2 text-sm rounded-md transition-colors hover:bg-red-900/50 text-[var(--color-danger)]">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                    <span>Clear Drawings</span>
                </button>
            </li>
        </ul>
    </div>
</div>
