// components/map-layer-control.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

export type MapLayer = 'Topo' | 'Street' | 'Dark' | 'Satellite';

@Component({
  selector: 'app-map-layer-control',
  templateUrl: './map-layer-control.component.html',
})
export class MapLayerControlComponent {
  @Input() currentLayer: MapLayer;
  @Output() layerChange = new EventEmitter<MapLayer>();

  isOpen = false;
  layerOptions: { id: MapLayer; name: string }[] = [
    { id: 'Topo', name: 'Topographic' },
    { id: 'Street', name: 'Street' },
    { id: 'Dark', name: 'Dark' },
    { id: 'Satellite', name: 'Satellite' },
  ];

  handleSelect(layer: MapLayer): void {
    this.layerChange.emit(layer);
    this.isOpen = false;
  }
}

<div class="relative">
    <button (click)="isOpen = !isOpen" class="p-2.5 rounded-full text-white w-12 h-12 flex items-center justify-center bg-slate-700 hover:bg-slate-600 shadow-lg transition-colors" aria-label="Change map layer" title="Change map layer">
        <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
    </button>
    <div *ngIf="isOpen" class="absolute bottom-full mb-2 right-0 w-40 bg-[var(--color-surface)] border border-[var(--color-surface-light)] rounded-lg shadow-lg animate-fade-in-fast">
        <ul class="p-1">
            <li *ngFor="let option of layerOptions">
                <button (click)="handleSelect(option.id)" class="w-full text-left px-3 py-2 text-sm rounded-md transition-colors" 
                    [ngClass]="currentLayer === option.id ? 'bg-[var(--color-accent)] text-white' : 'hover:bg-[var(--color-surface-light)] text-[var(--color-text-primary)]'">
                    {{ option.name }}
                </button>
            </li>
        </ul>
    </div>
</div>

// components/MapLayerControl.tsx
import React, { useState } from 'react';
import { Layers } from 'lucide-react';

export type MapLayer = 'Topo' | 'Street' | 'Dark' | 'Satellite';

interface MapLayerControlProps {
    currentLayer: MapLayer;
    onLayerChange: (layer: MapLayer) => void;
}

const layerOptions: { id: MapLayer; name: string }[] = [
    { id: 'Topo', name: 'Topographic' },
    { id: 'Street', name: 'Street' },
    { id: 'Dark', name: 'Dark' },
    { id: 'Satellite', name: 'Satellite' },
];

const MapLayerControl: React.FC<MapLayerControlProps> = ({ currentLayer, onLayerChange }) => {
    const [isOpen, setIsOpen] = useState(false);

    const handleSelect = (layer: MapLayer) => {
        onLayerChange(layer);
        setIsOpen(false);
    };

    return (
        <div className="relative">
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="p-2.5 rounded-full text-white w-12 h-12 flex items-center justify-center bg-slate-700 hover:bg-slate-600 shadow-lg transition-colors"
                aria-label="Change map layer"
                title="Change map layer"
            >
                <Layers className="h-5 w-5" />
            </button>

            {isOpen && (
                <div className="absolute bottom-full mb-2 right-0 w-40 bg-[var(--color-surface)] border border-[var(--color-surface-light)] rounded-lg shadow-lg animate-fade-in-fast">
                    <ul className="p-1">
                        {layerOptions.map((option) => (
                            <li key={option.id}>
                                <button
                                    onClick={() => handleSelect(option.id)}
                                    className={`w-full text-left px-3 py-2 text-sm rounded-md transition-colors ${
                                        currentLayer === option.id
                                            ? 'bg-[var(--color-accent)] text-white'
                                            : 'hover:bg-[var(--color-surface-light)] text-[var(--color-text-primary)]'
                                    }`}
                                >
                                    {option.name}
                                </button>
                            </li>
                        ))}
                    </ul>
                </div>
            )}
             <style>{`
                @keyframes fade-in-fast {
                    from { opacity: 0; transform: scale(0.95) translateY(10px); }
                    to { opacity: 1; transform: scale(1) translateY(0); }
                }
                .animate-fade-in-fast {
                    animation: fade-in-fast 0.1s ease-out forwards;
                }
            `}</style>
        </div>
    );
};

export default MapLayerControl;
