// components/MarkedPointsPanel.tsx
import React, { useRef, useEffect } from 'react';
import { MarkedPoint, CoordSystem } from '../types';
import { Trash2, Undo, LocateFixed, Pin, PlusCircle, Save, X } from 'lucide-react';
import { formatDistance } from '../services/measurementService';

interface MarkedPointsPanelProps {
    isOpen: boolean;
    onClosePanel: () => void;
    points: MarkedPoint[];
    coordSystem: CoordSystem;
    onAddCurrentLocation: () => void;
    onDelete: (id: string) => void;
    onUndo: () => void;
    onClear: () => void;
    onGoTo: (point: MarkedPoint) => void;
    onSaveRoute: () => void;
}

const PointRow: React.FC<{ point: MarkedPoint; coordSystem: CoordSystem; onDelete: (id: string) => void; onGoTo: (point: MarkedPoint) => void; }> = ({ point, coordSystem, onDelete, onGoTo }) => {
    const coords = coordSystem === CoordSystem.UTM_WGS84 ? point.coords.utm : point.coords.indianGrid;
    return (
        <div className="flex items-center justify-between p-1.5 rounded-md hover:bg-[var(--color-surface-lighter)]/50 transition-colors">
            <div className="flex items-center space-x-2">
                <span className="font-bold text-[var(--color-accent)] w-8 text-center">{point.name}</span>
                <div className="text-xs font-mono">
                    <p>{coords ? (coordSystem === CoordSystem.UTM_WGS84 && 'zone' in coords ? `${coords.zone}${coords.hemisphere} ${coords.easting.toFixed(0)} E ${coords.northing.toFixed(0)} N` : `${(coords as any).easting.toFixed(0)} E ${(coords as any).northing.toFixed(0)} N`) : 'Calculating...'}</p>
                    <p className="text-[var(--color-text-secondary)]">Total: {formatDistance(point.totalDistance)}</p>
                </div>
            </div>
            <div className="flex items-center">
                <button onClick={() => onGoTo(point)} className="p-1.5 rounded-full hover:bg-[var(--color-surface-light)] text-[var(--color-text-secondary)] hover:text-white" title="Navigate to point"><LocateFixed size={16}/></button>
                <button onClick={() => onDelete(point.id)} className="p-1.5 rounded-full hover:bg-red-900/50 text-[var(--color-danger)]" title="Delete point"><Trash2 size={16}/></button>
            </div>
        </div>
    );
};

const MarkedPointsPanel: React.FC<MarkedPointsPanelProps> = ({ isOpen, onClosePanel, points, coordSystem, onAddCurrentLocation, onDelete, onUndo, onClear, onGoTo, onSaveRoute }) => {
    const listRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
      if (listRef.current) listRef.current.scrollTop = listRef.current.scrollHeight;
    }, [points.length]);

    const totalDistance = points.length > 0 ? points[points.length - 1].totalDistance : 0;

    return (
        <div className={`fixed bottom-0 left-0 right-0 z-[1001] transition-transform duration-300 ease-in-out ${isOpen ? '-translate-y-16' : 'translate-y-full'}`}>
            <div className="marked-points-panel-content">
                <div className="flex items-center justify-between p-2 border-b border-[var(--color-surface-light)]">
                    <div className="flex items-center space-x-2 overflow-hidden">
                        <Pin className="text-[var(--color-accent)] flex-shrink-0" size={18}/>
                        <div>
                            <h3 className="font-bold text-sm leading-tight truncate">Route Planner</h3>
                            <p className="text-xs text-[var(--color-text-secondary)] leading-tight">{points.length} points, Total: {formatDistance(totalDistance)}</p>
                        </div>
                    </div>
                    <button onClick={onClosePanel} className="p-1.5 rounded-full hover:bg-red-900/50 text-[var(--color-danger)]" title="Close Planner"><X size={18} /></button>
                </div>
                <div ref={listRef} className="flex-grow overflow-y-auto p-2 max-h-[30vh]">
                    {points.length > 0 ? (
                        <div className="space-y-0.5">{points.map(p => <PointRow key={p.id} point={p} coordSystem={coordSystem} onDelete={onDelete} onGoTo={onGoTo} />)}</div>
                    ) : (
                        <div className="text-center py-6 text-[var(--color-text-secondary)]"><p className="text-sm">Tap on the map to add points.</p></div>
                    )}
                </div>
                <div className="flex-shrink-0 p-2 border-t border-[var(--color-surface-light)] bg-[var(--color-background)]/50 grid grid-cols-2 gap-1.5">
                    <button onClick={onAddCurrentLocation} className="button-secondary"><PlusCircle size={14} /><span>Add My Location</span></button>
                    <button onClick={onSaveRoute} disabled={points.length === 0} className="button-primary"><Save size={14} /><span>Save Route</span></button>
                </div>
            </div>
        </div>
    );
};

export default MarkedPointsPanel;

// components/marked-points-panel.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, AfterViewChecked } from '@angular/core';
import { MarkedPoint, CoordSystem } from '../types';
import { MeasurementService } from '../services/measurement.service';

@Component({
  selector: 'app-marked-points-panel',
  templateUrl: './marked-points-panel.component.html',
})
export class MarkedPointsPanelComponent implements AfterViewChecked {
  @Input() isOpen: boolean;
  @Input() points: MarkedPoint[] = [];
  @Input() coordSystem: CoordSystem;
  @Output() closePanel = new EventEmitter<void>();
  @Output() addCurrentLocation = new EventEmitter<void>();
  @Output() delete = new EventEmitter<string>();
  @Output() undo = new EventEmitter<void>();
  @Output() clear = new EventEmitter<void>();
  @Output() goTo = new EventEmitter<MarkedPoint>();
  @Output() saveRoute = new EventEmitter<void>();

  @ViewChild('list') private listRef: ElementRef;
  private shouldScroll = false;

  constructor(public measurementService: MeasurementService) {}

  ngAfterViewChecked() {
    if (this.shouldScroll) {
      this.scrollToBottom();
      this.shouldScroll = false;
    }
  }
  
  ngOnChanges() {
    this.shouldScroll = true;
  }
  
  private scrollToBottom(): void {
    try {
      this.listRef.nativeElement.scrollTop = this.listRef.nativeElement.scrollHeight;
    } catch(err) { }
  }

  get totalDistance(): number {
    return this.points.length > 0 ? this.points[this.points.length - 1].totalDistance : 0;
  }

  // FIX: Rewrote method to be type-safe and correctly handle UTM and Indian Grid coordinate systems.
  getCoordsString(point: MarkedPoint): string {
    if (this.coordSystem === CoordSystem.UTM_WGS84) {
      const coords = point.coords.utm;
      if (!coords) return 'Calculating...';
      return `${coords.zone}${coords.hemisphere} ${coords.easting.toFixed(0)} E ${coords.northing.toFixed(0)} N`;
    } else {
      const coords = point.coords.indianGrid;
      if (!coords) return 'Calculating...';
      return `${coords.easting.toFixed(0)} E ${coords.northing.toFixed(0)} N`;
    }
  }
}

<div class="fixed bottom-0 left-0 right-0 z-[1001] transition-transform duration-300 ease-in-out" 
    [class.-translate-y-16]="isOpen" [class.translate-y-full]="!isOpen">
    <div class="marked-points-panel-content">
        <div class="flex items-center justify-between p-2 border-b border-[var(--color-surface-light)]">
            <div class="flex items-center space-x-2 overflow-hidden">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-[var(--color-accent)] flex-shrink-0"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                <div>
                    <h3 class="font-bold text-sm leading-tight truncate">Route Planner</h3>
                    <p class="text-xs text-[var(--color-text-secondary)] leading-tight">{{ points.length }} points, Total: {{ measurementService.formatDistance(totalDistance) }}</p>
                </div>
            </div>
            <button (click)="closePanel.emit()" class="p-1.5 rounded-full hover:bg-red-900/50 text-[var(--color-danger)]" title="Close Planner">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
            </button>
        </div>
        <div #list class="flex-grow overflow-y-auto p-2 max-h-[30vh]">
            <div *ngIf="points.length > 0; else noPoints" class="space-y-0.5">
                <div *ngFor="let point of points" class="flex items-center justify-between p-1.5 rounded-md hover:bg-[var(--color-surface-lighter)]/50 transition-colors">
                    <div class="flex items-center space-x-2">
                        <span class="font-bold text-[var(--color-accent)] w-8 text-center">{{ point.name }}</span>
                        <div class="text-xs font-mono">
                            <p>{{ getCoordsString(point) }}</p>
                            <p class="text-[var(--color-text-secondary)]">Total: {{ measurementService.formatDistance(point.totalDistance) }}</p>
                        </div>
                    </div>
                    <div class="flex items-center">
                        <button (click)="goTo.emit(point)" class="p-1.5 rounded-full hover:bg-[var(--color-surface-light)] text-[var(--color-text-secondary)] hover:text-white" title="Navigate to point"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><circle cx="12" cy="12" r="8"></circle><line x1="12" y1="2" x2="12" y2="6"></line><line x1="12" y1="18" x2="12" y2="22"></line><line x1="2" y1="12" x2="6" y2="12"></line><line x1="18" y1="12" x2="22" y2="12"></line></svg></button>
                        <button (click)="delete.emit(point.id)" class="p-1.5 rounded-full hover:bg-red-900/50 text-[var(--color-danger)]" title="Delete point"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg></button>
                    </div>
                </div>
            </div>
            <ng-template #noPoints>
                <div class="text-center py-6 text-[var(--color-text-secondary)]"><p class="text-sm">Tap on the map to add points.</p></div>
            </ng-template>
        </div>
        <div class="flex-shrink-0 p-2 border-t border-[var(--color-surface-light)] bg-[var(--color-background)]/50 grid grid-cols-2 gap-1.5">
            <button (click)="addCurrentLocation.emit()" class="button-secondary"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg><span>Add My Location</span></button>
            <button (click)="saveRoute.emit()" [disabled]="points.length === 0" class="button-primary"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg><span>Save Route</span></button>
        </div>
    </div>
</div>
