// components/measurement-display.component.ts
import { Component, Input, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import * as L from 'leaflet';
import { DrawnShape, DrawingTool } from '../types';
import { MeasurementService } from '../services/measurement.service';

@Component({
  selector: 'app-measurement-display',
  template: '', // This component interacts directly with the map, no template needed
})
export class MeasurementDisplayComponent implements OnChanges, OnDestroy {
  @Input() map: L.Map;
  @Input() shapes: DrawnShape[];
  @Input() tempPoints: L.LatLng[];
  @Input() mousePos: L.LatLng | null;
  @Input() drawingTool: DrawingTool;
  @Input() drawingColor: string;
  @Input() drawingWeight: number;

  private layerGroup: L.LayerGroup;

  constructor(public measurementService: MeasurementService) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.map) return;
    
    if (!this.layerGroup) {
      this.layerGroup = L.layerGroup().addTo(this.map);
    }

    this.layerGroup.clearLayers();
    this.drawShapes();
    this.drawTemporaryShape();
  }

  ngOnDestroy(): void {
    if (this.layerGroup) {
      this.layerGroup.remove();
    }
  }

  private drawShapes(): void {
    this.shapes.forEach(shape => {
      if (shape.type === DrawingTool.Pen && shape.points.length > 1) {
        L.polyline(shape.points, { color: shape.color, weight: shape.weight, opacity: 0.9 })
          .addTo(this.layerGroup)
          .bindTooltip(`<strong>Distance:</strong> ${this.measurementService.formatDistance(shape.distance ?? 0)}`, {
            permanent: true,
            className: 'measurement-tooltip',
          });
      }
    });
  }

  private drawTemporaryShape(): void {
    if (this.drawingTool === DrawingTool.Pen && this.tempPoints.length > 0) {
      const pointsToDraw = this.mousePos ? [...this.tempPoints, this.mousePos] : this.tempPoints;
      L.polyline(pointsToDraw, { color: this.drawingColor, weight: this.drawingWeight, dashArray: '5, 5' }).addTo(this.layerGroup);

      if (this.mousePos) {
        const liveDistance = this.measurementService.calculateDistance(pointsToDraw);
        if (liveDistance > 0) {
          L.tooltip({ permanent: true, direction: 'right', offset: [10, 0], className: 'measurement-tooltip' })
            .setLatLng(this.mousePos)
            .setContent(`<div>${this.measurementService.formatDistance(liveDistance)}</div>`)
            .addTo(this.layerGroup);
        }
      }
    }
  }
}

// components/MeasurementDisplay.tsx
import React from 'react';
import { Polyline, Tooltip } from 'react-leaflet';
import { LatLng } from 'leaflet';
import { DrawnShape, DrawingTool } from '../types';
import { formatDistance, calculateDistance } from '../services/measurementService';

interface MeasurementDisplayProps {
    shapes: DrawnShape[];
    tempPoints: LatLng[];
    mousePos: LatLng | null;
    drawingTool: DrawingTool;
    drawingColor: string;
    drawingWeight: number;
}

const MeasurementDisplay: React.FC<MeasurementDisplayProps> = ({ shapes, tempPoints, mousePos, drawingTool, drawingColor, drawingWeight }) => {
    
    const getShapeStyle = (color: string, weight: number) => ({ color, weight, opacity: 0.9 });
    
    // Live calculation for tooltip
    let liveDistance = 0;
    if (drawingTool === DrawingTool.Pen && tempPoints.length > 0) {
        const pointsToMeasure = mousePos ? [...tempPoints, mousePos] : tempPoints;
        liveDistance = calculateDistance(pointsToMeasure);
    }

    return (
         <>
            <style>{`
                .measurement-tooltip {
                    background-color: var(--color-surface-light);
                    border: 1px solid var(--color-surface-lighter);
                    color: var(--color-text-primary);
                    padding: 4px 8px;
                    border-radius: 4px;
                    box-shadow: none;
                    font-family: var(--font-mono);
                    font-size: 12px;
                    text-align: center;
                }
            `}</style>
            {/* Render completed shapes and their measurements */}
            {shapes.map(shape => (
                <React.Fragment key={shape.id}>
                    {shape.type === DrawingTool.Pen && shape.points.length > 1 && (
                        <Polyline positions={shape.points} pathOptions={getShapeStyle(shape.color, shape.weight)}>
                            <Tooltip permanent className="measurement-tooltip">
                                <strong>Distance:</strong> {formatDistance(shape.distance ?? 0)}
                            </Tooltip>
                        </Polyline>
                    )}
                </React.Fragment>
            ))}

            {/* Render the shape being actively drawn */}
            {drawingTool === DrawingTool.Pen && tempPoints.length > 0 && (
                <>
                    {/* Render the temporary line */}
                    <Polyline positions={mousePos ? [...tempPoints, mousePos] : tempPoints} pathOptions={{ ...getShapeStyle(drawingColor, drawingWeight), dashArray: '5, 5' }} />
                    {/* Render live tooltip */}
                    {mousePos && liveDistance > 0 && (
                       <Tooltip
                            permanent
                            direction="right"
                            offset={[10, 0]}
                            position={mousePos}
                            className="measurement-tooltip"
                        >
                            <div>{formatDistance(liveDistance)}</div>
                        </Tooltip>
                    )}
                </>
            )}
        </>
    );
};

export default MeasurementDisplay;
