// components/offline-map-downloader.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Map as LeafletMap } from 'leaflet';
import { OfflineMapsService } from '../services/offline-maps.service';
import { MapUtilsService } from '../services/map-utils.service';
import { OfflineRegionInfo } from '../types';

const MAX_TILES_TO_DOWNLOAD = 5000;
const MIN_DOWNLOAD_ZOOM = 10;
const MAX_DOWNLOAD_ZOOM = 16;

@Component({
  selector: 'app-offline-map-downloader',
  templateUrl: './offline-map-downloader.component.html',
})
export class OfflineMapDownloaderComponent {
  @Input() isOpen: boolean;
  @Input() map: LeafletMap | null;
  @Input() currentTileUrl: string;
  @Output() close = new EventEmitter<void>();

  regions$ = this.offlineMapsService.regions$;
  regionName = '';
  isDownloading = false;
  progress = { current: 0, total: 0 };
  error: string | null = null;

  constructor(
    private offlineMapsService: OfflineMapsService,
    private mapUtils: MapUtilsService
  ) {}

  async handleDownload(): Promise<void> {
    if (!this.map || !this.regionName.trim()) {
      this.error = "Please provide a name for the region.";
      return;
    }
    this.error = null;
    this.isDownloading = true;
    this.progress = { current: 0, total: 0 };

    const bounds = this.map.getBounds();
    const minZoom = Math.max(MIN_DOWNLOAD_ZOOM, Math.floor(this.map.getZoom()));
    const maxZoom = MAX_DOWNLOAD_ZOOM;

    const urlsToDownload = this.mapUtils.getTileUrlsForBounds(bounds, minZoom, maxZoom, this.currentTileUrl);

    if (urlsToDownload.length > MAX_TILES_TO_DOWNLOAD || urlsToDownload.length === 0) {
      this.error = urlsToDownload.length > MAX_TILES_TO_DOWNLOAD 
        ? `Too many tiles (${urlsToDownload.length}). Please zoom in.`
        : "No tiles to download for this view.";
      this.isDownloading = false;
      return;
    }

    this.progress.total = urlsToDownload.length;
    for (const url of urlsToDownload) {
      try {
        await fetch(url, { mode: 'no-cors' });
      } catch (err) {
        console.warn(`Could not fetch tile ${url}:`, err);
      }
      this.progress.current++;
    }

    this.offlineMapsService.addRegion({
      name: this.regionName.trim(),
      bounds: { _southWest: bounds.getSouthWest(), _northEast: bounds.getNorthEast() },
      minZoom, maxZoom, tileCount: urlsToDownload.length, layerUrl: this.currentTileUrl,
    });
    this.regionName = '';
    this.isDownloading = false;
  }

  handleDelete(region: OfflineRegionInfo): void {
    if (window.confirm(`Are you sure you want to delete "${region.name}"?`)) {
      this.offlineMapsService.deleteRegion(region.id);
    }
  }
}

<div *ngIf="isOpen" class="absolute inset-0 bg-black/75 z-[1200] flex items-center justify-center" (click)="close.emit()">
    <div class="bg-[var(--color-surface)] text-white rounded-lg shadow-2xl w-11/12 max-w-md p-4 animate-fade-in border border-[var(--color-surface-light)]" (click)="$event.stopPropagation()">
        <div class="flex justify-between items-center border-b border-[var(--color-surface-light)] pb-2 mb-3">
            <h2 class="text-lg font-bold">Offline Maps</h2>
            <button (click)="close.emit()" class="p-1 rounded-full hover:bg-[var(--color-surface-light)]"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></button>
        </div>
        
        <div class="bg-[var(--color-background)] p-3 rounded-md border border-[var(--color-surface-light)]">
            <h3 class="text-sm font-semibold mb-2 text-[var(--color-accent)]">Download Current View</h3>
            <p class="text-xs text-[var(--color-text-secondary)] mb-3">
                Save map tiles for the current screen area (zoom {{ map ? (map.getZoom() | floor) : 10 }}-16).
            </p>
            <input type="text" placeholder="Name for this region..." [(ngModel)]="regionName" [disabled]="isDownloading" class="w-full bg-[var(--color-surface-light)] p-2 rounded border border-[var(--color-surface-lighter)] focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] mb-2"/>
            <button (click)="handleDownload()" [disabled]="isDownloading || !regionName.trim()" class="w-full flex items-center justify-center space-x-2 bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white font-bold py-2 px-4 rounded transition-colors disabled:opacity-50 disabled:cursor-wait">
                 <svg *ngIf="isDownloading" class="animate-spin" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="2" x2="12" y2="6"></line><line x1="12" y1="18" x2="12" y2="22"></line><line x1="4.93" y1="4.93" x2="7.76" y2="7.76"></line><line x1="16.24" y1="16.24" x2="19.07" y2="19.07"></line><line x1="2" y1="12" x2="6" y2="12"></line><line x1="18" y1="12" x2="22" y2="12"></line><line x1="4.93" y1="19.07" x2="7.76" y2="16.24"></line><line x1="16.24" y1="7.76" x2="19.07" y2="4.93"></line></svg>
                 <svg *ngIf="!isDownloading" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                 <span>{{ isDownloading ? 'Downloading... (' + progress.current + '/' + progress.total + ')' : 'Download' }}</span>
            </button>
            <div *ngIf="isDownloading" class="w-full bg-gray-600 rounded-full h-1.5 mt-2">
                <div class="bg-[var(--color-accent-hover)] h-1.5 rounded-full" [style.width.%]="progress.total > 0 ? (progress.current / progress.total) * 100 : 0"></div>
            </div>
            <p *ngIf="error" class="text-xs text-red-400 mt-2">{{ error }}</p>
        </div>

        <div class="mt-4">
             <h3 class="text-sm font-semibold mb-2">Saved Regions</h3>
             <div class="space-y-2 max-h-48 overflow-y-auto pr-2">
                <div *ngIf="(regions$ | async) as regions">
                    <div *ngIf="regions.length > 0; else noRegions">
                        <div *ngFor="let region of regions" class="flex items-center justify-between p-2 rounded-md bg-white/5">
                            <div>
                                <p class="font-bold text-sm">{{ region.name }}</p>
                                <p class="text-xs font-mono text-[var(--color-text-secondary)]">{{ region.tileCount }} tiles (Zoom {{ region.minZoom }}-{{ region.maxZoom }})</p>
                            </div>
                            <button (click)="handleDelete(region)" class="p-1.5 rounded-full hover:bg-red-900/50 text-[var(--color-danger)]" title="Delete region"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg></button>
                        </div>
                    </div>
                    <ng-template #noRegions><p class="text-center text-sm text-[var(--color-text-secondary)] py-4">No offline regions saved.</p></ng-template>
                </div>
             </div>
        </div>
    </div>
</div>

// components/OfflineMapDownloader.tsx
import React, { useState, useCallback } from 'react';
import { LatLngBounds, Map as LeafletMap } from 'leaflet';
import { X, Download, Trash2, Loader } from 'lucide-react';
import useOfflineMaps from '../hooks/useOfflineMaps';
import { getTileUrlsForBounds } from '../services/mapUtils';
import { OfflineRegionInfo } from '../types';

const MAX_TILES_TO_DOWNLOAD = 5000; // Safety limit
const MIN_DOWNLOAD_ZOOM = 10;
const MAX_DOWNLOAD_ZOOM = 16;


interface OfflineMapDownloaderProps {
    isOpen: boolean;
    onClose: () => void;
    map: LeafletMap | null;
    currentTileUrl: string;
}

const OfflineMapDownloader: React.FC<OfflineMapDownloaderProps> = ({ isOpen, onClose, map, currentTileUrl }) => {
    const { regions, addRegion, deleteRegion } = useOfflineMaps();
    const [regionName, setRegionName] = useState('');
    const [isDownloading, setIsDownloading] = useState(false);
    const [progress, setProgress] = useState({ current: 0, total: 0 });
    const [error, setError] = useState<string | null>(null);

    const handleDownload = useCallback(async () => {
        if (!map || !regionName.trim()) {
            setError("Please provide a name for the region.");
            return;
        }
        setError(null);
        setIsDownloading(true);
        setProgress({ current: 0, total: 0 });

        const bounds = map.getBounds();
        const minZoom = Math.max(MIN_DOWNLOAD_ZOOM, Math.floor(map.getZoom()));
        const maxZoom = MAX_DOWNLOAD_ZOOM;

        const urlsToDownload = getTileUrlsForBounds(bounds, minZoom, maxZoom, currentTileUrl);

        if (urlsToDownload.length > MAX_TILES_TO_DOWNLOAD) {
            setError(`Too many tiles to download (${urlsToDownload.length}). Please zoom in or select a smaller area.`);
            setIsDownloading(false);
            return;
        }
        
        if (urlsToDownload.length === 0) {
            setError("No tiles to download for the current view and zoom levels.");
            setIsDownloading(false);
            return;
        }

        setProgress({ current: 0, total: urlsToDownload.length });

        let downloadedCount = 0;
        for (const url of urlsToDownload) {
            try {
                // Fetching the tile will trigger the service worker to cache it.
                // We use { mode: 'no-cors' } because we don't need to read the response,
                // and it can prevent CORS issues with some tile servers.
                await fetch(url, { mode: 'no-cors' });
            } catch (err) {
                console.warn(`Could not fetch tile ${url}:`, err);
                // Continue even if some tiles fail
            }
            downloadedCount++;
            setProgress({ current: downloadedCount, total: urlsToDownload.length });
        }

        addRegion({
            name: regionName.trim(),
            bounds: { // Convert to plain object for serialization
                _southWest: bounds.getSouthWest(),
                _northEast: bounds.getNorthEast(),
            },
            minZoom,
            maxZoom,
            tileCount: urlsToDownload.length,
            layerUrl: currentTileUrl,
        });

        setRegionName('');
        setIsDownloading(false);

    }, [map, regionName, currentTileUrl, addRegion]);

    const handleDelete = (region: OfflineRegionInfo) => {
        if (!window.confirm(`Are you sure you want to delete the offline region "${region.name}"?`)) {
            return;
        }
        const bounds = new LatLngBounds(region.bounds._southWest, region.bounds._northEast);
        const urlsToDelete = getTileUrlsForBounds(bounds, region.minZoom, region.maxZoom, region.layerUrl);
        deleteRegion(region.id, urlsToDelete);
    };
    
    if (!isOpen) return null;
    
    return (
        <div className="absolute inset-0 bg-black/75 z-[1200] flex items-center justify-center" onClick={onClose}>
            <div className="bg-[var(--color-surface)] text-white rounded-lg shadow-2xl w-11/12 max-w-md p-4 animate-fade-in border border-[var(--color-surface-light)]" onClick={(e) => e.stopPropagation()}>
                <div className="flex justify-between items-center border-b border-[var(--color-surface-light)] pb-2 mb-3">
                    <h2 className="text-lg font-bold">Offline Maps</h2>
                    <button onClick={onClose} className="p-1 rounded-full hover:bg-[var(--color-surface-light)]"><X size={20} /></button>
                </div>
                
                <div className="bg-[var(--color-background)] p-3 rounded-md border border-[var(--color-surface-light)]">
                    <h3 className="text-sm font-semibold mb-2 text-[var(--color-accent)]">Download Current View</h3>
                    <p className="text-xs text-[var(--color-text-secondary)] mb-3">
                        Save map tiles for the current screen area (zoom {map ? Math.max(MIN_DOWNLOAD_ZOOM, Math.floor(map.getZoom())) : MIN_DOWNLOAD_ZOOM}-{MAX_DOWNLOAD_ZOOM}).
                    </p>
                    <input
                        type="text"
                        placeholder="Name for this region..."
                        value={regionName}
                        onChange={(e) => setRegionName(e.target.value)}
                        disabled={isDownloading}
                        className="w-full bg-[var(--color-surface-light)] p-2 rounded border border-[var(--color-surface-lighter)] focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] mb-2"
                    />
                    <button 
                        onClick={handleDownload}
                        disabled={isDownloading || !regionName.trim()}
                        className="w-full flex items-center justify-center space-x-2 bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white font-bold py-2 px-4 rounded transition-colors disabled:opacity-50 disabled:cursor-wait"
                    >
                         {isDownloading ? <Loader className="animate-spin" size={20} /> : <Download size={20} />}
                         <span>{isDownloading ? `Downloading... (${progress.current}/${progress.total})` : 'Download'}</span>
                    </button>
                    {isDownloading && (
                        <div className="w-full bg-gray-600 rounded-full h-1.5 mt-2">
                            <div className="bg-[var(--color-accent-hover)] h-1.5 rounded-full" style={{ width: progress.total > 0 ? `${(progress.current / progress.total) * 100}%` : '0%' }}></div>
                        </div>
                    )}
                    {error && <p className="text-xs text-red-400 mt-2">{error}</p>}
                </div>

                <div className="mt-4">
                     <h3 className="text-sm font-semibold mb-2">Saved Regions</h3>
                     <div className="space-y-2 max-h-48 overflow-y-auto pr-2">
                        {regions.length > 0 ? regions.map(region => (
                            <div key={region.id} className="flex items-center justify-between p-2 rounded-md bg-white/5">
                                <div>
                                    <p className="font-bold text-sm">{region.name}</p>
                                    <p className="text-xs font-mono text-[var(--color-text-secondary)]">
                                        {region.tileCount} tiles (Zoom {region.minZoom}-{region.maxZoom})
                                    </p>
                                </div>
                                <button onClick={() => handleDelete(region)} className="p-1.5 rounded-full hover:bg-red-900/50 text-[var(--color-danger)]" title="Delete region"><Trash2 size={16}/></button>
                            </div>
                        )) : (
                            <p className="text-center text-sm text-[var(--color-text-secondary)] py-4">No offline regions saved.</p>
                        )}
                     </div>
                </div>

            </div>
        </div>
    );
};

export default OfflineMapDownloader;
