// components/sun-moon-page.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { Subscription } from 'rxjs';
import { LatLng } from 'leaflet';
// FIX: GeolocationState is imported from types.ts, not from the service.
import { GeolocationService } from '../services/geolocation.service';
import { GeolocationState } from '../types';
import { AstroService, SunTimes } from '../services/astro.service';
import { CoordService } from '../services/coord.service';
import { IndianGridZone, IndianGridCoordinates } from '../types';

interface AstroData {
  sunTimes: SunTimes;
  moonTimes: { rise?: Date; set?: Date; alwaysUp?: boolean; alwaysDown?: boolean; };
  indianGrid: IndianGridCoordinates | null;
}

@Component({
  selector: 'app-sun-moon-page',
  templateUrl: './sun-moon-page.component.html',
})
export class SunMoonPageComponent implements OnInit, OnDestroy {
  date = new Date();
  location: GeolocationState;
  astroData: AstroData | null = null;
  private geoSub: Subscription;

  // Moon display state
  moonDisplayHour = new Date().getHours();
  moonDisplayDate = new Date();
  moonPositionData: any;
  moonIlluminationData: any;

  constructor(
    private geolocationService: GeolocationService,
    private astroService: AstroService,
    private coordService: CoordService,
    private cd: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    this.geoSub = this.geolocationService.location$.subscribe(location => {
      this.location = location;
      this.calculateAstroData();
    });
  }

  ngOnDestroy(): void {
    this.geoSub.unsubscribe();
  }

  onDateChange(dateString: string): void {
    if (dateString) {
      this.date = new Date(dateString);
      this.calculateAstroData();
    }
  }

  calculateAstroData(): void {
    if (this.location?.lat !== null && this.location?.lon !== null) {
      this.astroData = {
        sunTimes: this.astroService.getTimes(this.date, this.location.lat, this.location.lon),
        moonTimes: this.astroService.getMoonTimes(this.date, this.location.lat, this.location.lon),
        indianGrid: this.coordService.convertLatLonToIndianGrid(new LatLng(this.location.lat, this.location.lon), IndianGridZone.IIA)
      };
      this.updateMoonDisplayData();
    }
  }

  updateMoonDisplayData(): void {
    if (!this.location?.lat || !this.location?.lon) return;
    this.moonDisplayDate = new Date(this.date);
    this.moonDisplayDate.setHours(this.moonDisplayHour, 0, 0, 0);
    this.moonPositionData = this.astroService.getMoonPosition(this.moonDisplayDate, this.location.lat, this.location.lon);
    this.moonIlluminationData = this.astroService.getMoonIllumination(this.moonDisplayDate);
    this.cd.detectChanges();
  }

  formatTime(d?: Date): string {
    return d && !isNaN(d.getTime()) ? d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '--:--';
  }

  formatDateInput(d: Date): string {
    const tz_offset = d.getTimezoneOffset() * 60000;
    return new Date(d.getTime() - tz_offset).toISOString().slice(0, 16);
  }

  getPhaseName(p: number): string {
    if (p < 0.03 || p > 0.97) return "New Moon";
    if (p < 0.22) return "Waxing Crescent";
    if (p < 0.28) return "First Quarter";
    if (p < 0.47) return "Waxing Gibbous";
    if (p < 0.53) return "Full Moon";
    if (p < 0.72) return "Waning Gibbous";
    if (p < 0.78) return "Last Quarter";
    return "Waning Crescent";
  }

  getSliderBackground(): string {
    if (!this.astroData?.moonTimes) return '#374151';
    const { alwaysUp, alwaysDown, rise, set } = this.astroData.moonTimes;
    if (alwaysUp) return 'linear-gradient(to right, #fbbf24 0%, #fbbf24 100%)';
    if (alwaysDown) return 'linear-gradient(to right, #374151 0%, #374151 100%)';
    const riseHour = rise?.getHours();
    const setHour = set?.getHours();
    if (riseHour === undefined || setHour === undefined) return '#374151';

    const rP = (riseHour / 23) * 100, sP = (setHour / 23) * 100;
    if (riseHour < setHour) return `linear-gradient(to right, #374151 ${rP}%, #fbbf24 ${rP}%, #fbbf24 ${sP}%, #374151 ${sP}%)`;
    return `linear-gradient(to right, #fbbf24 ${sP}%, #374151 ${sP}%, #374151 ${rP}%, #fbbf24 ${rP}%)`;
  }
}

<div class="h-full w-full bg-[var(--color-background)] text-white p-2 sm:p-4 flex flex-col overflow-y-auto">
    <h1 class="text-xl font-bold text-center text-[var(--color-accent-hover)] mb-4">Sun & Moon</h1>
    <div class="bg-[var(--color-surface)] p-3 rounded-lg mb-4 border border-[var(--color-surface-light)]">
        <div class="flex flex-col sm:flex-row gap-4 justify-between items-center">
            <div class="flex items-center text-sm">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-[var(--color-text-secondary)] mr-2 flex-shrink-0"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                <div class="font-mono text-xs">
                    <div *ngIf="location?.lat !== null && location?.lon !== null; else gettingLocation">
                        <p>Lat/Lon: {{ location.lat.toFixed(4) }}, {{ location.lon.toFixed(4) }}</p>
                        <p class="text-[var(--color-text-secondary)]">Indian Grid: {{ astroData?.indianGrid ? astroData.indianGrid.easting.toFixed(0) + 'E ' + astroData.indianGrid.northing.toFixed(0) + 'N' : '...' }}</p>
                    </div>
                    <ng-template #gettingLocation><span class="animate-pulse">{{ location?.error || 'Getting location...' }}</span></ng-template>
                </div>
            </div>
            <input type="datetime-local" [value]="formatDateInput(date)" (change)="onDateChange($any($event.target).value)" class="input-field font-mono text-sm"/>
        </div>
    </div>
    <div *ngIf="!astroData" class="flex-grow flex items-center justify-center"><p class="text-[var(--color-text-secondary)] animate-pulse">Waiting for location data...</p></div>
    
    <ng-container *ngIf="astroData">
        <div class="grid md:grid-cols-2 gap-4">
            <!-- Sun Info Card -->
            <div class="bg-[var(--color-surface)] p-4 rounded-lg border border-[var(--color-surface-light)] h-full flex flex-col">
                <h2 class="text-lg font-bold text-[var(--color-accent)] flex items-center mb-3">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>
                    <span class="ml-2">Sun</span>
                </h2>
                <!-- Sun Timeline to be implemented as a component -->
                <div class="pt-2 border-t border-[var(--color-surface-light)]/50">
                     <div class="flex justify-between items-center text-sm py-1">
                        <span class="text-[var(--color-text-secondary)]">Sunrise</span>
                        <span class="font-mono font-bold text-[var(--color-text-primary)] text-right">
                           <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="inline mr-2 text-[var(--color-text-secondary)]"><path d="M17 18a5 5 0 0 0-10 0"/><line x1="12" y1="2" x2="12" y2="9"/><line x1="4.22" y1="10.22" x2="5.64" y2="11.64"/><line x1="1" y1="18" x2="3" y2="18"/><line x1="21" y1="18" x2="23" y2="18"/><line x1="18.36" y1="11.64" x2="19.78" y2="10.22"/><line x1="23" y1="22" x2="1" y2="22"/><polyline points="8 6 12 2 16 6"/></svg>
                           {{ formatTime(astroData.sunTimes.sunrise) }}
                        </span>
                    </div>
                     <div class="flex justify-between items-center text-sm py-1">
                        <span class="text-[var(--color-text-secondary)]">Sunset</span>
                        <span class="font-mono font-bold text-[var(--color-text-primary)] text-right">
                          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="inline mr-2 text-[var(--color-text-secondary)]"><path d="M17 18a5 5 0 0 0-10 0"/><line x1="12" y1="9" x2="12" y2="2"/><line x1="4.22" y1="10.22" x2="5.64" y2="11.64"/><line x1="1" y1="18" x2="3" y2="18"/><line x1="21" y1="18" x2="23" y2="18"/><line x1="18.36" y1="11.64" x2="19.78" y2="10.22"/><line x1="23" y1="22" x2="1" y2="22"/><polyline points="16 5 12 9 8 5"/></svg>
                          {{ formatTime(astroData.sunTimes.sunset) }}
                        </span>
                    </div>
                </div>
            </div>

            <!-- Moon Info Card -->
            <div class="bg-[var(--color-surface)] p-4 rounded-lg border border-[var(--color-surface-light)] h-full flex flex-col">
                 <h2 class="text-lg font-bold text-[var(--color-accent)] flex items-center mb-3">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>
                    <span class="ml-2">Moon</span>
                </h2>
                <div *ngIf="moonIlluminationData && moonPositionData" class="flex-grow">
                    <!-- Moon Display Component -->
                    <div class="flex items-center gap-4">
                        <!-- Moon Phase SVG to be implemented -->
                        <div class="flex-grow space-y-1 text-sm">
                            <p class="font-bold text-base text-[var(--color-accent-hover)]">{{ getPhaseName(moonIlluminationData.phase) }}</p>
                            <p><span class="text-[var(--color-text-secondary)]">Illumination:</span> {{ (moonIlluminationData.fraction * 100).toFixed(1) }}%</p>
                            <p class="font-mono bg-black/20 px-2 py-1 rounded w-fit text-lg">{{ moonDisplayDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }}</p>
                        </div>
                    </div>
                    <div class="pt-2 mt-2">
                        <input type="range" min="0" max="23" step="1" [value]="moonDisplayHour" (input)="moonDisplayHour = $any($event.target).value; updateMoonDisplayData()" class="w-full h-2 rounded-lg appearance-none cursor-pointer slider-thumb" [style.background]="getSliderBackground()" />
                        <div class="flex justify-between text-xs text-[var(--color-text-secondary)] mt-1"><span>00:00</span><span>12:00</span><span>23:00</span></div>
                    </div>
                    <div class="pt-2 mt-2 border-t border-[var(--color-surface-light)] grid grid-cols-2 gap-x-4 text-sm">
                        <div class="flex justify-between items-center text-sm py-1"><span class="text-[var(--color-text-secondary)]">Azimuth</span><span class="font-mono font-bold text-[var(--color-text-primary)] text-right">{{ ((moonPositionData.azimuth * 180 / Math.PI + 180) % 360).toFixed(1) }}°</span></div>
                        <div class="flex justify-between items-center text-sm py-1"><span class="text-[var(--color-text-secondary)]">Altitude</span><span class="font-mono font-bold text-[var(--color-text-primary)] text-right">{{ (moonPositionData.altitude * 180 / Math.PI).toFixed(1) }}°</span></div>
                    </div>
                </div>
                <div class="pt-2 border-t border-[var(--color-surface-light)]/50">
                    <div *ngIf="astroData.moonTimes.alwaysUp"><div class="flex justify-between items-center text-sm py-1"><span class="text-[var(--color-text-secondary)]">Visibility</span><span class="font-mono font-bold text-[var(--color-text-primary)] text-right">Always Up</span></div></div>
                    <div *ngIf="astroData.moonTimes.alwaysDown"><div class="flex justify-between items-center text-sm py-1"><span class="text-[var(--color-text-secondary)]">Visibility</span><span class="font-mono font-bold text-[var(--color-text-primary)] text-right">Always Down</span></div></div>
                    <ng-container *ngIf="!astroData.moonTimes.alwaysUp && !astroData.moonTimes.alwaysDown">
                        <div class="flex justify-between items-center text-sm py-1"><span class="text-[var(--color-text-secondary)]">Moonrise</span><span class="font-mono font-bold text-[var(--color-text-primary)] text-right">{{ formatTime(astroData.moonTimes.rise) }}</span></div>
                        <div class="flex justify-between items-center text-sm py-1"><span class="text-[var(--color-text-secondary)]">Moonset</span><span class="font-mono font-bold text-[var(--color-text-primary)] text-right">{{ formatTime(astroData.moonTimes.set) }}</span></div>
                    </ng-container>
                </div>
            </div>
        </div>
        <!-- Calendar Component to be implemented -->
    </ng-container>
</div>

// components/SunMoonPage.tsx
import React, { useState, useMemo } from 'react';
import { LatLng } from 'leaflet';
import useGeolocation from '../hooks/useGeolocation';
import * as AstroService from '../services/astroService';
import { convertLatLonToIndianGrid } from '../services/coordService';
import { IndianGridZone } from '../types';
import { Sun, Moon, Sunrise, Sunset, MapPin, ChevronLeft, ChevronRight } from 'lucide-react';

const InfoCard: React.FC<{ title: string; icon: React.ReactNode; children: React.ReactNode }> = ({ title, icon, children }) => (
    <div className="bg-[var(--color-surface)] p-4 rounded-lg border border-[var(--color-surface-light)] h-full flex flex-col">
        <h2 className="text-lg font-bold text-[var(--color-accent)] flex items-center mb-3">{icon}<span className="ml-2">{title}</span></h2>
        <div className="space-y-2 flex-grow flex flex-col">{children}</div>
    </div>
);

const InfoRow: React.FC<{ label: string; value: string | React.ReactNode }> = ({ label, value }) => (
    <div className="flex justify-between items-center text-sm py-1"><span className="text-[var(--color-text-secondary)]">{label}</span><span className="font-mono font-bold text-[var(--color-text-primary)] text-right">{value}</span></div>
);

const SunTimeline: React.FC<{ times: AstroService.SunTimes }> = ({ times }) => {
    const timelineEvents = useMemo(() => {
        const dayStart = new Date(times.solarNoon).setHours(0, 0, 0, 0);
        const toPercent = (d: Date) => (d.getTime() - dayStart) / 864000;
        const events = [
            { name: 'Night', start: 0, end: toPercent(times.nightEnd), color: '#1e3a8a' },
            { name: 'Astronomical', start: toPercent(times.nightEnd), end: toPercent(times.nauticalDawn), color: '#312e81' },
            { name: 'Nautical', start: toPercent(times.nauticalDawn), end: toPercent(times.dawn), color: '#4c1d95' },
            { name: 'Civil', start: toPercent(times.dawn), end: toPercent(times.sunrise), color: '#86198f' },
            { name: 'Daylight', start: toPercent(times.sunrise), end: toPercent(times.sunset), color: 'var(--color-accent)' },
            { name: 'Civil', start: toPercent(times.sunset), end: toPercent(times.dusk), color: '#86198f' },
            { name: 'Nautical', start: toPercent(times.dusk), end: toPercent(times.nauticalDusk), color: '#4c1d95' },
            { name: 'Astronomical', start: toPercent(times.nauticalDusk), end: toPercent(times.night), color: '#312e81' },
            { name: 'Night', start: toPercent(times.night), end: 100, color: '#1e3a8a' },
        ];
        return events.filter(e => e.start < e.end && !isNaN(e.start) && !isNaN(e.end));
    }, [times]);
    return (
        <div className="w-full mt-2">
            <div className="h-4 w-full flex rounded overflow-hidden shadow-inner bg-black/20">{timelineEvents.map((e, i) => <div key={i} title={e.name} style={{ width: `${e.end - e.start}%`, backgroundColor: e.color }} />)}</div>
            <div className="flex justify-between text-xs text-gray-400 mt-1"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div>
        </div>
    );
};

const MoonPhase: React.FC<{ phase: number; angle: number; size?: number }> = ({ phase, angle, size = 80 }) => {
    const r = size / 2;
    const path = useMemo(() => {
        const arc = Math.abs(2 * phase - 1);
        const rx = (1 - arc) * r;
        const largeArc = (phase > 0.25 && phase < 0.75) ? 1 : 0;
        const sweep = 1;
        if (phase > 0.495 && phase < 0.505) return `M 0,${r} A ${r},${r} 0 1 1 ${size},${r} A ${r},${r} 0 1 1 0,${r}`;
        return `M ${r},${0} A ${r},${r} 0 1,1 ${r},${size} A ${rx},${r} 0 ${largeArc},${sweep} ${r},${0} Z`;
    }, [phase, r, size]);
    const transform = phase > 0.5 ? `scale(-1, 1) translate(${-size}, 0)` : '';

    return (
        <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} className="mx-auto my-1 drop-shadow-lg">
            <defs><filter id="glow" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="1.5" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>
            <circle cx={r} cy={r} r={r} fill="#4b5563" />
            <g transform={`rotate(${(angle * 180 / Math.PI) - 90}, ${r}, ${r})`}><g transform={transform}><path d={path} fill="#f9fafb" filter="url(#glow)" /></g></g>
        </svg>
    );
};

const MoonDisplay: React.FC<{
    baseDate: Date; lat: number; lon: number;
    moonTimes: { rise?: Date; set?: Date; alwaysUp?: boolean; alwaysDown?: boolean };
}> = ({ baseDate, lat, lon, moonTimes }) => {
    const [hour, setHour] = useState(() => new Date().toDateString() === baseDate.toDateString() ? new Date().getHours() : 12);
    const currentDate = useMemo(() => { const d = new Date(baseDate); d.setHours(hour, 0, 0, 0); return d; }, [baseDate, hour]);
    const moonData = useMemo(() => ({ ...AstroService.getMoonIllumination(currentDate), ...AstroService.getMoonPosition(currentDate, lat, lon) }), [currentDate, lat, lon]);
    const getPhaseName = (p:number) => p<0.03||p>0.97?"New Moon":p<0.22?"Waxing Crescent":p<0.28?"First Quarter":p<0.47?"Waxing Gibbous":p<0.53?"Full Moon":p<0.72?"Waning Gibbous":p<0.78?"Last Quarter":"Waning Crescent";

    const sliderBackground = useMemo(() => {
        if (moonTimes.alwaysUp) return 'linear-gradient(to right, #fbbf24 0%, #fbbf24 100%)';
        if (moonTimes.alwaysDown) return 'linear-gradient(to right, #374151 0%, #374151 100%)';
        const riseHour = moonTimes.rise?.getHours();
        const setHour = moonTimes.set?.getHours();
        if (riseHour === undefined || setHour === undefined) return '#374151';

        const rP = (riseHour / 23) * 100, sP = (setHour / 23) * 100;
        if (riseHour < setHour) return `linear-gradient(to right, #374151 ${rP}%, #fbbf24 ${rP}%, #fbbf24 ${sP}%, #374151 ${sP}%)`;
        return `linear-gradient(to right, #fbbf24 ${sP}%, #374151 ${sP}%, #374151 ${rP}%, #fbbf24 ${rP}%)`;
    }, [moonTimes]);

    return (
        <>
            <div className="flex items-center gap-4">
                <MoonPhase phase={moonData.phase} angle={moonData.angle} />
                <div className="flex-grow space-y-1 text-sm">
                    <p className="font-bold text-base text-[var(--color-accent-hover)]">{getPhaseName(moonData.phase)}</p>
                    <p><span className="text-[var(--color-text-secondary)]">Illumination:</span> {(moonData.fraction * 100).toFixed(1)}%</p>
                    <p className="font-mono bg-black/20 px-2 py-1 rounded w-fit text-lg">{currentDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p>
                </div>
            </div>
            <div className="pt-2 mt-2">
                <input type="range" min="0" max="23" step="1" value={hour} onChange={(e) => setHour(parseInt(e.target.value))} className="w-full h-2 rounded-lg appearance-none cursor-pointer slider-thumb" style={{ background: sliderBackground }} />
                <div className="flex justify-between text-xs text-[var(--color-text-secondary)] mt-1"><span>00:00</span><span>12:00</span><span>23:00</span></div>
            </div>
            <div className="pt-2 mt-2 border-t border-[var(--color-surface-light)] grid grid-cols-2 gap-x-4 text-sm">
                <InfoRow label="Azimuth" value={`${((moonData.azimuth * 180 / Math.PI + 180) % 360).toFixed(1)}°`} />
                <InfoRow label="Altitude" value={`${(moonData.altitude * 180 / Math.PI).toFixed(1)}°`} />
            </div>
            <style>{`.slider-thumb::-webkit-slider-thumb { -webkit-appearance: none; appearance: none; width: 16px; height: 16px; background: #fff; border-radius: 50%; border: 2px solid #9ca3af; cursor: pointer; margin-top: -6px; }`}</style>
        </>
    );
};

const MonthlyCalendar: React.FC<{ selectedDate: Date; onDateSelect: (date: Date) => void; lat: number; lon: number }> = ({ selectedDate, onDateSelect, lat, lon }) => {
    const [displayDate, setDisplayDate] = useState(new Date(selectedDate.getFullYear(), selectedDate.getMonth(), 1));
    const changeMonth = (offset: number) => setDisplayDate(current => { const newDate = new Date(current); newDate.setMonth(newDate.getMonth() + offset); return newDate; });

    const calendarGrid = useMemo(() => {
        const year = displayDate.getFullYear(), month = displayDate.getMonth();
        const firstDay = new Date(year, month, 1).getDay(), daysInMonth = new Date(year, month + 1, 0).getDate();
        const grid = Array.from({ length: firstDay }, () => null);
        for (let i = 1; i <= daysInMonth; i++) {
            const date = new Date(year, month, i, 12, 0, 0); // use noon for average phase
            const illum = AstroService.getMoonIllumination(date);
            grid.push({ date: i, phase: illum.phase, angle: illum.angle });
        }
        return grid;
    }, [displayDate, lat, lon]);

    return (
        <div className="bg-[var(--color-surface)] p-3 sm:p-4 rounded-lg border border-[var(--color-surface-light)] mt-4">
            <div className="flex justify-between items-center mb-3">
                <button onClick={() => changeMonth(-1)} className="p-2 rounded-full hover:bg-[var(--color-surface-light)]"><ChevronLeft/></button>
                <h3 className="text-lg font-bold text-center">{displayDate.toLocaleString('default', { month: 'long' })} {displayDate.getFullYear()}</h3>
                <button onClick={() => changeMonth(1)} className="p-2 rounded-full hover:bg-[var(--color-surface-light)]"><ChevronRight/></button>
            </div>
            <div className="grid grid-cols-7 gap-1 text-center text-xs text-[var(--color-text-secondary)] mb-2 font-bold">
                {['S', 'M', 'T', 'W', 'T', 'F', 'S'].map(d => <div key={d}>{d}</div>)}
            </div>
            <div className="grid grid-cols-7 gap-1">
                {calendarGrid.map((day, index) => (
                    <div key={index} className="aspect-square">
                        {day && (
                            <button
                                onClick={() => onDateSelect(new Date(displayDate.getFullYear(), displayDate.getMonth(), day.date))}
                                className={`w-full h-full rounded-lg flex flex-col items-center justify-center transition-colors ${selectedDate.toDateString() === new Date(displayDate.getFullYear(), displayDate.getMonth(), day.date).toDateString() ? 'bg-[var(--color-accent)] text-white' : 'hover:bg-[var(--color-surface-light)]'}`}>
                                <span className="text-xs font-bold">{day.date}</span>
                                <MoonPhase phase={day.phase} angle={day.angle} size={24} />
                            </button>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

const SunMoonPage: React.FC = () => {
    const [date, setDate] = useState(() => new Date());
    const { lat, lon, error: geoError } = useGeolocation();
    const astroData = useMemo(() => {
        if (lat === null || lon === null) return null;
        return {
            sunTimes: AstroService.getTimes(date, lat, lon),
            moonTimes: AstroService.getMoonTimes(date, lat, lon),
            indianGrid: convertLatLonToIndianGrid(new LatLng(lat, lon), IndianGridZone.IIA)
        };
    }, [date, lat, lon]);

    const formatTime = (d?: Date) => d && !isNaN(d.getTime()) ? d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '--:--';
    const formatDateInput = (d: Date) => { const tz_offset = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - tz_offset).toISOString().slice(0, 16); };

    return (
        <div className="h-full w-full bg-[var(--color-background)] text-white p-2 sm:p-4 flex flex-col overflow-y-auto">
            <h1 className="text-xl font-bold text-center text-[var(--color-accent-hover)] mb-4">Sun & Moon</h1>
            <div className="bg-[var(--color-surface)] p-3 rounded-lg mb-4 border border-[var(--color-surface-light)]">
                <div className="flex flex-col sm:flex-row gap-4 justify-between items-center">
                    <div className="flex items-center text-sm"><MapPin size={16} className="text-[var(--color-text-secondary)] mr-2 flex-shrink-0" />
                        <div className="font-mono text-xs">
                            {lat !== null && lon !== null ? (<><p>Lat/Lon: {lat.toFixed(4)}, {lon.toFixed(4)}</p><p className="text-[var(--color-text-secondary)]">Indian Grid: {astroData?.indianGrid ? `${astroData.indianGrid.easting.toFixed(0)}E ${astroData.indianGrid.northing.toFixed(0)}N` : '...'}</p></>) : (<span className="animate-pulse">{geoError || 'Getting location...'}</span>)}
                        </div>
                    </div>
                    <input type="datetime-local" value={formatDateInput(date)} onChange={(e) => {if(e.target.value) setDate(new Date(e.target.value))}} className="input-field font-mono text-sm"/>
                </div>
            </div>
            {!astroData ? <div className="flex-grow flex items-center justify-center"><p className="text-[var(--color-text-secondary)] animate-pulse">Waiting for location data...</p></div> : (
                <>
                    <div className="grid md:grid-cols-2 gap-4">
                        <InfoCard title="Sun" icon={<Sun size={20} />}><div className="flex-grow"><SunTimeline times={astroData.sunTimes} /></div><div className="pt-2 border-t border-[var(--color-surface-light)]/50"><InfoRow label="Sunrise" value={<><Sunrise size={16} className="inline mr-2 text-[var(--color-text-secondary)]"/> {formatTime(astroData.sunTimes.sunrise)}</>} /><InfoRow label="Sunset" value={<><Sunset size={16} className="inline mr-2 text-[var(--color-text-secondary)]"/> {formatTime(astroData.sunTimes.sunset)}</>} /></div></InfoCard>
                        <InfoCard title="Moon" icon={<Moon size={20} />}>
                            <div className="flex-grow"><MoonDisplay baseDate={date} lat={lat!} lon={lon!} moonTimes={astroData.moonTimes} /></div>
                            <div className="pt-2 border-t border-[var(--color-surface-light)]/50">
                                {astroData.moonTimes.alwaysUp ? ( <InfoRow label="Visibility" value="Always Up" /> ) : astroData.moonTimes.alwaysDown ? ( <InfoRow label="Visibility" value="Always Down" /> ) : (
                                    <>
                                        <InfoRow label="Moonrise" value={formatTime(astroData.moonTimes.rise)} />
                                        <InfoRow label="Moonset" value={formatTime(astroData.moonTimes.set)} />
                                    </>
                                )}
                            </div>
                        </InfoCard>
                    </div>
                    <MonthlyCalendar selectedDate={date} onDateSelect={setDate} lat={lat!} lon={lon!} />
                </>
            )}
        </div>
    );
};

export default SunMoonPage;
